Repository anita00001/fix-mate-backend, pull requests merged in 2023-10, with the labels that each got.

#22 Item-details-model
  Gemfile.lock
  app/models/specialization.rb
  db/migrate/20231027091012_create_experts.rb
  db/migrate/20231027144942_create_specializations.rb
  db/migrate/20231027145723_add_specialization_to_experts.rb
  db/schema.rb
  test/fixtures/specializations.yml
Labels: backend

#25 Fixes and reservation model
  app/models/reservation.rb
  db/migrate/20231029101958_remove_image_from_experts.rb
  db/migrate/20231029102044_remove_icon_from_specializations.rb
  db/migrate/20231029103445_create_reservations.rb
  db/schema.rb
  test/fixtures/reservations.yml
Labels: backend, fixes

#29 Add name and Role Column on User Table
  db/migrate/20231027025010_create_users.rb
  db/migrate/20231030075500_add_name_role_to_users.rb
  db/schema.rb
Labels: backend

#31 Add expert
  app/controllers/experts_controller.rb
  app/models/specialization.rb
  config/routes.rb
Labels: backend

#32 Reservation API endpoint with GET and POST action
  app/controllers/api/v1/reservations_controller.rb
  config/routes.rb
  test/controllers/api/v1/reservations_controller_test.rb
Labels: backend, API endpoint, controller

#36 Setup api endpoint
  app/controllers/api/v1/experts_controller.rb
  config/routes.rb
Labels: API endpoint

#38 Api-documentation
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/experts_controller.rb
  app/controllers/api/v1/users_controller.rb
  config/credentials.yml.enc
  config/initializers/rswag_api.rb
  config/initializers/rswag_ui.rb
  config/routes.rb
  spec/rails_helper.rb
  spec/requests/api/v1/experts_spec.rb
  spec/requests/api/v1/reservations_spec.rb
  spec/requests/api/v1/users_spec.rb
  spec/swagger_helper.rb
  swagger/v1/swagger.yaml
Labels: backend
